### ISSUE TITLE
Parser.swift errors

### ISSUE THREAD

**Issue by onepayclick** [vapor-community/HTMLKit-Components#14]
Hi :)

I'm aware the package is not fully released but I was trying to play around with it and I'm getting these errors
![image](https://user-images.githubusercontent.com/64233519/182970682-84a445ef-d59c-4726-b974-9eecf986deee.png)

My package.swift is 
![image](https://user-images.githubusercontent.com/64233519/182970959-ffd4428b-07a4-4cd3-9193-56ed1491aa59.png)

// swift-tools-version:5.6

**Comment by mattesmohr** [comment]
Ah, my bad. I forgot to add the import for the linux environment. I will make it up to you on the weekend.

```swift
#if canImport(FoundationXML)
import FoundationXML
#endif
```

**Comment by mattesmohr** [comment]
I have released a patch (0.1.1). It should work now.
